### ISSUE TITLE
[SPELL/WARRIOR/FURY] Bloodthirst

### ISSUE THREAD

**Issue by lingxDEV** [ProjectSkyfire/SkyFire_548#1015]
**Current behaviour:**

[Bloodthirst](https://mop-shoot.tauri.hu/?spell=23881) does not heal, and does not have a doubled chance to crit.

**Expected behaviour:**

Bloodthirst should heal 1% of hp and have a doubled chance to crit.

**Steps to reproduce the problem:**

Video example:
https://streamable.com/askoul

As you can see in the video, I have 50%+ crit which means Bloodthirst should 100% be a critical strike.
You can see my health does not go up when using Bloodthirst.

**SF rev. hash/commit:** 

Skyfire rev. 0e61f8a904c9

**SFDB version:**  

stable5

**Operating system:** 

win10 64

**Comment by AriDEV** [comment]
the critical isnt shown in the combat log for some reason however you can see the numbers in your vod. yellow numbers are criticals white numbers are non crits.
critical hits double the damage. which is happening its just not shown in the log. however you have a lot of Overkills due to your training dummy being 1HP.

The non crit meele:
Your Melee hit Training Dummy 1 Physical (8473 Overkill)
The Crit meele:
Your Melee hit Training Dummy 1 Physical (17719 Overkill)

Because your vod does only have 1 bloodthirst its hard to compare however it was yellow so i guess it was a crit.

**Comment by AriDEV** [comment]
4f4eb13e34cd9849c507577afc68bbabf24f727e

**Comment by lingxDEV** [comment]
It can crit, I just showed it didn't 100% of the times (which is should when having 50% crit)
