### ISSUE TITLE
Dungeon Finder.

### ISSUE THREAD

**Issue by YukkiKun** [ProjectSkyfire/SkyFire_548#1077]
**Description:**

I don't know if the dungeon finder is working but i found 2 issues.

**Current behaviour:**

You can't leave the queue. to leave the queue you have to relog

You don't get listed as your role.

**Expected behaviour:**

You should be able to leave the queue without relog and when you queue up for your role you should get listed even if you are the only one queueing

**Steps to reproduce the problem:**

1. You need level 15 to use the Dungeon Finder
2. Choose a dungeon or random dungeon finder
3. Try to leave the queue or wait to get listed but nothing happends.

**SFDB version:**  5.4.8 21.0

**Operating system:** Windows 7 x64

**Comment by Crypticaz** [comment]
I believe dungeon finder has a few issues, this being one of them

**Comment by iCry1337** [comment]
Can confirm, you would be able to delist from the tool. also the reward tooltip is wrong.

**Comment by AriDEV** [comment]
the issue here with leaving the dungeon finder is that the client message sends player guid aka leader guid of a group.
and then we pass the leader guid to Leavelfg function which can get 2 guids. groupguid, playerguid. if we pass groupguid gguid is groupguid, if we pass playerguid IS_GROUP_GUID is false and we call GetGroup() but as a solo player you not in a group. thats why solo player cant leave the LFG queue. if you in group you also passing leaderguid aka playerguid. which also calls GetGroup()
but then its not NULL and the queue leave is possible if you queued as group.

**Comment by AriDEV** [comment]
by generating a random group in the packet just to get a non NULL group pointer for the solo player and then leaving the queue and disbanding the group works to leave the queue. but...
